language: ruby
cache: bundler
rvm:
  - 1.9.3
services: postgresql
before_script:
  - psql -c 'create database ci_test;' -U postgres
  - sqlite3 ci_test ''

env:
  - DATATASK_ENV=postgresql_test
  - DATATASK_ENV=sqlite_test

notifications:
  email:
    on_success: never
    on_failure: change
