language: ruby
rvm:
  - 1.9.3
services: postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - "cp config/database.yml.test config/database.yml"
notifications:
  email:
    on_success: never
    on_failure: change
